# Unique name for this workflow
name: CI

# Definition when the workflow should run
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - 'sfdx-project.json'
            - 'README.md'

# Jobs to be executed
jobs:
    format-lint-lwc-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
         
         # Install Prettier 
        - name: 'Install Prettier'
          run: npm install -g prettier

        # Prettier formatting
        - name: 'Code formatting verification with Prettier'
          run: npm run prettier:verify

        # Install Salesforce CLI
        #- name: Install Salesforce CLI
        #  run: |
        #    npm install sfdx-cli
        #    node_modules/sfdx-cli/bin/run --version
        #    node_modules/sfdx-cli/bin/run plugins --core

        # Run Apex test
        #- name: Run Apex test
        #  run: node_modules/sfdx-cli/bin/run force:apex:test:run -c -r human
  
             
     
      